# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: prex/base/v1/mypy_ext.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bprex/base/v1/mypy_ext.proto\x12\x0cprex.base.v1\x1a google/protobuf/descriptor.proto\",\n\x0cPytypeImport\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0e\n\x06module\x18\x02 \x01(\t:P\n\rpytype_import\x12\x1c.google.protobuf.FileOptions\x18\x91N \x03(\x0b\x32\x1a.prex.base.v1.PytypeImport:.\n\x06pytype\x12\x1d.google.protobuf.FieldOptions\x18\x92N \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'prex.base.v1.mypy_ext_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:
  google_dot_protobuf_dot_descriptor__pb2.FileOptions.RegisterExtension(pytype_import)
  google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(pytype)

  DESCRIPTOR._options = None
  _PYTYPEIMPORT._serialized_start=79
  _PYTYPEIMPORT._serialized_end=123
# @@protoc_insertion_point(module_scope)
